Um atributo idade deve conter valores entre 0 e 120 para domínio do problema. Se algum valor desse atributo está fora desse intervalo, temos que tomar uma decisão sobre ele: deixar ele como desconhecido (NaN no numpy), escolher algum valor para ele, ou tentar encontrar o valor verdadeiro baseado em outros atributos ou instâncias.

In [1]:
import numpy as np

In [2]:
import numpy as np

In [3]:
import numpy as np
idades = np.array([10,20,34,-25,50,165,71,55,30,34], dtype = np.float32)

In [4]:
desconhecido = np.NaN
idades = np.where(np.logical_or(idades < 0, idades > 120), desconhecido, idades)

In [5]:
idades

array([10., 20., 34., nan, 50., nan, 71., 55., 30., 34.], dtype=float32)

In [6]:
desconhecido

nan

Por exemplo, um atributo de temperatura possui um valor de média de 26 graus com desvio padrão de 2 graus.
Considerando uma distribuição normal espera-se que 68.25%
estejam a uma unidade de desvio-padrão e 99.73%
a três unidades.
Se encontrar um valor acima de unidades de desvio padrão, por exemplo, 32 graus, podemos tomar alguma decisão com esse valor.

In [7]:
temperatura = np.array([26.6, 27.8, 25.6, 26.2, 120.0, 20.4, 29.4, 24.4, 26.9, 26.7])
media = 26
desvio = 2

In [8]:
temperatura = np.where( ( np.abs(temperatura - media)/desvio ) > 3, media, temperatura )

In [9]:
temperatura

array([26.6, 27.8, 25.6, 26.2, 26. , 20.4, 29.4, 24.4, 26.9, 26.7])

Exemplo no conjunto de dados Iris

In [10]:
import pandas as pd
from sklearn import datasets
iris = datasets.load_iris()
data = pd.DataFrame(iris['data'], columns = iris['feature_names'])
data

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
16                 5.4               3.9                1.3               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
22                 4.6               3.6                1.0               0.2
23                 5.1               3.3                1.7               0.5
24                 4.8               3.4                1.9               0.2
25                 5.0               3.0                1.6               0.2
26                 5.0               3.4                1.6               0.4
27                 5.2               3.5                1.5               0.2
28                 5.2               3.4                1.4               0.2
29                 4.7               3.2                1.6               0.2
..                 ...               ...                ...               ...
120                6.9               3.2                5.7               2.3
121                5.6               2.8                4.9               2.0
122                7.7               2.8                6.7               2.0
123                6.3               2.7                4.9               1.8
124                6.7               3.3                5.7               2.1
125                7.2               3.2                6.0               1.8
126                6.2               2.8                4.8               1.8
127                6.1               3.0                4.9               1.8
128                6.4               2.8                5.6               2.1
129                7.2               3.0                5.8               1.6
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.5               1.8
138                6.0               3.0                4.8               1.8
139                6.9               3.1                5.4               2.1
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
142                5.8               2.7                5.1               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

Estatística Descritiva

In [11]:
data.describe().round(5)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.00000,150.00000,150.0000,150.00000
mean,5.84333,3.05733,3.7580,1.19933
std,0.82807,0.43587,1.7653,0.76224
min,4.30000,2.00000,1.0000,0.10000
25%,5.10000,2.80000,1.6000,0.30000
50%,5.80000,3.00000,4.3500,1.30000
75%,6.40000,3.30000,5.1000,1.80000
max,7.90000,4.40000,6.9000,2.50000

Definição de uma função para normalização linear

In [12]:
def normalizacao_linear(x):
    return (x - np.min(x)) / (np.max(x) - np.min(x));

Aplicação da função em uma das colunas do conjunto de dados

In [13]:
new_data = normalizacao_linear(data['sepal length (cm)'])
new_data

0      0.222222
1      0.166667
2      0.111111
3      0.083333
4      0.194444
5      0.305556
6      0.083333
7      0.194444
8      0.027778
9      0.166667
10     0.305556
11     0.138889
12     0.138889
13     0.000000
14     0.416667
15     0.388889
16     0.305556
17     0.222222
18     0.388889
19     0.222222
20     0.305556
21     0.222222
22     0.083333
23     0.222222
24     0.138889
25     0.194444
26     0.194444
27     0.250000
28     0.250000
29     0.111111
         ...
120    0.722222
121    0.361111
122    0.944444
123    0.555556
124    0.666667
125    0.805556
126    0.527778
127    0.500000
128    0.583333
129    0.805556
130    0.861111
131    1.000000
132    0.583333
133    0.555556
134    0.500000
135    0.944444
136    0.555556
137    0.583333
138    0.472222
139    0.722222
140    0.666667
141    0.722222
142    0.416667
143    0.694444
144    0.666667
145    0.666667
146    0.555556
147    0.611111
148    0.527778
149    0.444444
Name: sepal length (cm), Length: 150, dtype: float64

Aplicação da função em todas as colunas no conjunto de dados

axis = 0 aplica a função a todas as colunas. pegando o mínimo e máximo de cada atributo e não axis = 1 que aplicaria função a cada linha. o que envolveria outros atributos

In [14]:
new_data = data.apply(normalizacao_linear, axis = 0);
new_data

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.222222          0.625000           0.067797          0.041667
1             0.166667          0.416667           0.067797          0.041667
2             0.111111          0.500000           0.050847          0.041667
3             0.083333          0.458333           0.084746          0.041667
4             0.194444          0.666667           0.067797          0.041667
5             0.305556          0.791667           0.118644          0.125000
6             0.083333          0.583333           0.067797          0.083333
7             0.194444          0.583333           0.084746          0.041667
8             0.027778          0.375000           0.067797          0.041667
9             0.166667          0.458333           0.084746          0.000000
10            0.305556          0.708333           0.084746          0.041667
11            0.138889          0.583333           0.101695          0.041667
12            0.138889          0.416667           0.067797          0.000000
13            0.000000          0.416667           0.016949          0.000000
14            0.416667          0.833333           0.033898          0.041667
15            0.388889          1.000000           0.084746          0.125000
16            0.305556          0.791667           0.050847          0.125000
17            0.222222          0.625000           0.067797          0.083333
18            0.388889          0.750000           0.118644          0.083333
19            0.222222          0.750000           0.084746          0.083333
20            0.305556          0.583333           0.118644          0.041667
21            0.222222          0.708333           0.084746          0.125000
22            0.083333          0.666667           0.000000          0.041667
23            0.222222          0.541667           0.118644          0.166667
24            0.138889          0.583333           0.152542          0.041667
25            0.194444          0.416667           0.101695          0.041667
26            0.194444          0.583333           0.101695          0.125000
27            0.250000          0.625000           0.084746          0.041667
28            0.250000          0.583333           0.067797          0.041667
29            0.111111          0.500000           0.101695          0.041667
..                 ...               ...                ...               ...
120           0.722222          0.500000           0.796610          0.916667
121           0.361111          0.333333           0.661017          0.791667
122           0.944444          0.333333           0.966102          0.791667
123           0.555556          0.291667           0.661017          0.708333
124           0.666667          0.541667           0.796610          0.833333
125           0.805556          0.500000           0.847458          0.708333
126           0.527778          0.333333           0.644068          0.708333
127           0.500000          0.416667           0.661017          0.708333
128           0.583333          0.333333           0.779661          0.833333
129           0.805556          0.416667           0.813559          0.625000
130           0.861111          0.333333           0.864407          0.750000
131           1.000000          0.750000           0.915254          0.791667
132           0.583333          0.333333           0.779661          0.875000
133           0.555556          0.333333           0.694915          0.583333
134           0.500000          0.250000           0.779661          0.541667
135           0.944444          0.416667           0.864407          0.916667
136           0.555556          0.583333           0.779661          0.958333
137           0.583333          0.458333           0.762712          0.708333
138           0.472222          0.416667           0.644068          0.708333
139           0.722222          0.458333           0.745763          0.833333
140           0.666667          0.458333           0.779661          0.958333
141           0.722222          0.458333           0.694915          0.916667
142           0.416667          0.291667           0.694915          0.750000
143           0.694444          0.500000           0.830508          0.916667
144           0.666667          0.541667           0.796610          1.000000
145           0.666667          0.416667           0.711864          0.916667
146           0.555556          0.208333           0.677966          0.750000
147           0.611111          0.416667           0.711864          0.791667
148           0.527778          0.583333           0.745763          0.916667
149           0.444444          0.416667           0.694915          0.708333

[150 rows x 4 columns]

In [15]:
def normalizacaoDesvioPadrao(x):
    return ((x - np.mean(x)) / (np.std(x)));

In [16]:
new_data2 = data.apply(normalizacaoDesvioPadrao, axis = 0);

In [17]:
new_data2

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
5            -0.537178          1.939791          -1.169714         -1.052180
6            -1.506521          0.788808          -1.340227         -1.183812
7            -1.021849          0.788808          -1.283389         -1.315444
8            -1.748856         -0.362176          -1.340227         -1.315444
9            -1.143017          0.098217          -1.283389         -1.447076
10           -0.537178          1.479398          -1.283389         -1.315444
11           -1.264185          0.788808          -1.226552         -1.315444
12           -1.264185         -0.131979          -1.340227         -1.447076
13           -1.870024         -0.131979          -1.510739         -1.447076
14           -0.052506          2.169988          -1.453901         -1.315444
15           -0.173674          3.090775          -1.283389         -1.052180
16           -0.537178          1.939791          -1.397064         -1.052180
17           -0.900681          1.019004          -1.340227         -1.183812
18           -0.173674          1.709595          -1.169714         -1.183812
19           -0.900681          1.709595          -1.283389         -1.183812
20           -0.537178          0.788808          -1.169714         -1.315444
21           -0.900681          1.479398          -1.283389         -1.052180
22           -1.506521          1.249201          -1.567576         -1.315444
23           -0.900681          0.558611          -1.169714         -0.920548
24           -1.264185          0.788808          -1.056039         -1.315444
25           -1.021849         -0.131979          -1.226552         -1.315444
26           -1.021849          0.788808          -1.226552         -1.052180
27           -0.779513          1.019004          -1.283389         -1.315444
28           -0.779513          0.788808          -1.340227         -1.315444
29           -1.385353          0.328414          -1.226552         -1.315444
..                 ...               ...                ...               ...
120           1.280340          0.328414           1.103783          1.448832
121          -0.294842         -0.592373           0.649083          1.053935
122           2.249683         -0.592373           1.672157          1.053935
123           0.553333         -0.822570           0.649083          0.790671
124           1.038005          0.558611           1.103783          1.185567
125           1.643844          0.328414           1.274295          0.790671
126           0.432165         -0.592373           0.592246          0.790671
127           0.310998         -0.131979           0.649083          0.790671
128           0.674501         -0.592373           1.046945          1.185567
129           1.643844         -0.131979           1.160620          0.527406
130           1.886180         -0.592373           1.331133          0.922303
131           2.492019          1.709595           1.501645          1.053935
132           0.674501         -0.592373           1.046945          1.317199
133           0.553333         -0.592373           0.762758          0.395774
134           0.310998         -1.052767           1.046945          0.264142
135           2.249683         -0.131979           1.331133          1.448832
136           0.553333          0.788808           1.046945          1.580464
137           0.674501          0.098217           0.990108          0.790671
138           0.189830         -0.131979           0.592246          0.790671
139           1.280340          0.098217           0.933271          1.185567
140           1.038005          0.098217           1.046945          1.580464
141           1.280340          0.098217           0.762758          1.448832
142          -0.052506         -0.822570           0.762758          0.922303
143           1.159173          0.328414           1.217458          1.448832
144           1.038005          0.558611           1.103783          1.712096
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

In [18]:
new_data2.describe().round(5)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.00000,150.00000,150.00000,150.00000
mean,-0.00000,-0.00000,-0.00000,-0.00000
std,1.00335,1.00335,1.00335,1.00335
min,-1.87002,-2.43395,-1.56758,-1.44708
25%,-0.90068,-0.59237,-1.22655,-1.18381
50%,-0.05251,-0.13198,0.33648,0.13251
75%,0.67450,0.55861,0.76276,0.79067
max,2.49202,3.09078,1.78583,1.71210

In [19]:
def normalizacao_valor_maximo(x):
    return x / np.max(np.abs(x));

In [20]:
new_data3 = data.apply(normalizacao_valor_maximo, axis = 0);
new_data3

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.645570          0.795455           0.202899              0.08
1             0.620253          0.681818           0.202899              0.08
2             0.594937          0.727273           0.188406              0.08
3             0.582278          0.704545           0.217391              0.08
4             0.632911          0.818182           0.202899              0.08
5             0.683544          0.886364           0.246377              0.16
6             0.582278          0.772727           0.202899              0.12
7             0.632911          0.772727           0.217391              0.08
8             0.556962          0.659091           0.202899              0.08
9             0.620253          0.704545           0.217391              0.04
10            0.683544          0.840909           0.217391              0.08
11            0.607595          0.772727           0.231884              0.08
12            0.607595          0.681818           0.202899              0.04
13            0.544304          0.681818           0.159420              0.04
14            0.734177          0.909091           0.173913              0.08
15            0.721519          1.000000           0.217391              0.16
16            0.683544          0.886364           0.188406              0.16
17            0.645570          0.795455           0.202899              0.12
18            0.721519          0.863636           0.246377              0.12
19            0.645570          0.863636           0.217391              0.12
20            0.683544          0.772727           0.246377              0.08
21            0.645570          0.840909           0.217391              0.16
22            0.582278          0.818182           0.144928              0.08
23            0.645570          0.750000           0.246377              0.20
24            0.607595          0.772727           0.275362              0.08
25            0.632911          0.681818           0.231884              0.08
26            0.632911          0.772727           0.231884              0.16
27            0.658228          0.795455           0.217391              0.08
28            0.658228          0.772727           0.202899              0.08
29            0.594937          0.727273           0.231884              0.08
..                 ...               ...                ...               ...
120           0.873418          0.727273           0.826087              0.92
121           0.708861          0.636364           0.710145              0.80
122           0.974684          0.636364           0.971014              0.80
123           0.797468          0.613636           0.710145              0.72
124           0.848101          0.750000           0.826087              0.84
125           0.911392          0.727273           0.869565              0.72
126           0.784810          0.636364           0.695652              0.72
127           0.772152          0.681818           0.710145              0.72
128           0.810127          0.636364           0.811594              0.84
129           0.911392          0.681818           0.840580              0.64
130           0.936709          0.636364           0.884058              0.76
131           1.000000          0.863636           0.927536              0.80
132           0.810127          0.636364           0.811594              0.88
133           0.797468          0.636364           0.739130              0.60
134           0.772152          0.590909           0.811594              0.56
135           0.974684          0.681818           0.884058              0.92
136           0.797468          0.772727           0.811594              0.96
137           0.810127          0.704545           0.797101              0.72
138           0.759494          0.681818           0.695652              0.72
139           0.873418          0.704545           0.782609              0.84
140           0.848101          0.704545           0.811594              0.96
141           0.873418          0.704545           0.739130              0.92
142           0.734177          0.613636           0.739130              0.76
143           0.860759          0.727273           0.855072              0.92
144           0.848101          0.750000           0.826087              1.00
145           0.848101          0.681818           0.753623              0.92
146           0.797468          0.568182           0.724638              0.76
147           0.822785          0.681818           0.753623              0.80
148           0.784810          0.772727           0.782609              0.92
149           0.746835          0.681818           0.739130              0.72

[150 rows x 4 columns]

In [21]:
new_data3.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,0.739662,0.694848,0.544638,0.479733
std,0.104818,0.099061,0.255840,0.304895
min,0.544304,0.454545,0.144928,0.040000
25%,0.645570,0.636364,0.231884,0.120000
50%,0.734177,0.681818,0.630435,0.520000
75%,0.810127,0.750000,0.739130,0.720000
max,1.000000,1.000000,1.000000,1.000000

In [22]:

j = np.ceil( np.log10(997))

In [23]:
def normalizacao_escala_decimal(x):
    j = np.ceil( np.log10(np.max(np.abs(x) ) ) )
    return x / 10**j
data.apply(normalizacao_escala_decimal, axis = 0)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 0.51              0.35               0.14              0.02
1                 0.49              0.30               0.14              0.02
2                 0.47              0.32               0.13              0.02
3                 0.46              0.31               0.15              0.02
4                 0.50              0.36               0.14              0.02
5                 0.54              0.39               0.17              0.04
6                 0.46              0.34               0.14              0.03
7                 0.50              0.34               0.15              0.02
8                 0.44              0.29               0.14              0.02
9                 0.49              0.31               0.15              0.01
10                0.54              0.37               0.15              0.02
11                0.48              0.34               0.16              0.02
12                0.48              0.30               0.14              0.01
13                0.43              0.30               0.11              0.01
14                0.58              0.40               0.12              0.02
15                0.57              0.44               0.15              0.04
16                0.54              0.39               0.13              0.04
17                0.51              0.35               0.14              0.03
18                0.57              0.38               0.17              0.03
19                0.51              0.38               0.15              0.03
20                0.54              0.34               0.17              0.02
21                0.51              0.37               0.15              0.04
22                0.46              0.36               0.10              0.02
23                0.51              0.33               0.17              0.05
24                0.48              0.34               0.19              0.02
25                0.50              0.30               0.16              0.02
26                0.50              0.34               0.16              0.04
27                0.52              0.35               0.15              0.02
28                0.52              0.34               0.14              0.02
29                0.47              0.32               0.16              0.02
..                 ...               ...                ...               ...
120               0.69              0.32               0.57              0.23
121               0.56              0.28               0.49              0.20
122               0.77              0.28               0.67              0.20
123               0.63              0.27               0.49              0.18
124               0.67              0.33               0.57              0.21
125               0.72              0.32               0.60              0.18
126               0.62              0.28               0.48              0.18
127               0.61              0.30               0.49              0.18
128               0.64              0.28               0.56              0.21
129               0.72              0.30               0.58              0.16
130               0.74              0.28               0.61              0.19
131               0.79              0.38               0.64              0.20
132               0.64              0.28               0.56              0.22
133               0.63              0.28               0.51              0.15
134               0.61              0.26               0.56              0.14
135               0.77              0.30               0.61              0.23
136               0.63              0.34               0.56              0.24
137               0.64              0.31               0.55              0.18
138               0.60              0.30               0.48              0.18
139               0.69              0.31               0.54              0.21
140               0.67              0.31               0.56              0.24
141               0.69              0.31               0.51              0.23
142               0.58              0.27               0.51              0.19
143               0.68              0.32               0.59              0.23
144               0.67              0.33               0.57              0.25
145               0.67              0.30               0.52              0.23
146               0.63              0.25               0.50              0.19
147               0.65              0.30               0.52              0.20
148               0.62              0.34               0.54              0.23
149               0.59              0.30               0.51              0.18

[150 rows x 4 columns]

Mapeamento direto (Discretização)

In [24]:
np.random.seed(1)
genero = np.random.randint(low = 0, high = 3, size = 20)
genero

array([1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 2, 1, 2, 0, 2, 1, 2, 0, 0])

In [25]:
df = pd.DataFrame( {'genero': genero} )
df

    genero
0        1
1        0
2        0
3        1
4        1
5        0
6        0
7        1
8        0
9        1
10       0
11       2
12       1
13       2
14       0
15       2
16       1
17       2
18       0
19       0

In [26]:
df['genero_categoria'] = df.genero.replace(to_replace = {0 : 'Masculino', 1 : 'Feminino', 2 : 'Outro'})
df

    genero genero_categoria
0        1         Feminino
1        0        Masculino
2        0        Masculino
3        1         Feminino
4        1         Feminino
5        0        Masculino
6        0        Masculino
7        1         Feminino
8        0        Masculino
9        1         Feminino
10       0        Masculino
11       2            Outro
12       1         Feminino
13       2            Outro
14       0        Masculino
15       2            Outro
16       1         Feminino
17       2            Outro
18       0        Masculino
19       0        Masculino

Outra maneira de usar o To_Replace

In [27]:
to_replace = {
    0 : 'Masculino',
    1 : 'Feminino',
    2 : 'Outro'
}
print(to_replace)
print('type: ', type(to_replace) )

{0: 'Masculino', 1: 'Feminino', 2: 'Outro'}
type:  <class 'dict'>

In [28]:
df['genero_categoria'] = df.genero.replace(to_replace = to_replace)
df

    genero genero_categoria
0        1         Feminino
1        0        Masculino
2        0        Masculino
3        1         Feminino
4        1         Feminino
5        0        Masculino
6        0        Masculino
7        1         Feminino
8        0        Masculino
9        1         Feminino
10       0        Masculino
11       2            Outro
12       1         Feminino
13       2            Outro
14       0        Masculino
15       2            Outro
16       1         Feminino
17       2            Outro
18       0        Masculino
19       0        Masculino

Mapeamento de Intervalos

In [29]:
np.random.seed(1)
idade = np.random.randint(low = 0, high = 100, size = 20)
df = pd.DataFrame({'idade': idade})
df

    idade
0      37
1      12
2      72
3       9
4      75
5       5
6      79
7      64
8      16
9       1
10     76
11     71
12      6
13     25
14     50
15     20
16     18
17     84
18     11
19     28

In [30]:
def get_discretized_idade(x):
    if(x < 12):
        return 0
    elif(x< 18):
        return 1
    elif(x < 40):
        return 2
    elif(x < 60):
        return 3
    else:
        return 4

In [31]:
df['idade_discretizado'] = df.idade.apply(get_discretized_idade)
df

    idade  idade_discretizado
0      37                   2
1      12                   1
2      72                   4
3       9                   0
4      75                   4
5       5                   0
6      79                   4
7      64                   4
8      16                   1
9       1                   0
10     76                   4
11     71                   4
12      6                   0
13     25                   2
14     50                   3
15     20                   2
16     18                   2
17     84                   4
18     11                   0
19     28                   2

Intervalos de Igual Tamanho (ou largura fixa) L = max(x) - min(x) + 1 / K
Ii=[(min(x)+L×i),(min(x)+L×(i+1)−1],para1≤i<k

In [32]:
np.random.seed(1)
idade = np.random.randint(low = 1, high = 101, size = 500)
print(idade)

[ 38  13  73  10  76   6  80  65  17   2  77  72   7  26  51  21  19  85
  12  29  30  15  51  69  88  88  95  97  87  14  10   8  64  62  23  58
   2   1  61  82   9  89  14  48  73  31  72   4  71  22  50  58   4  69
  25  44  77  27  53  81  42  83  16  65  69  26  99  88   8  27  26  23
  10  68  24  28  38  58  84  39   9  33  35  11  24  16  88  26  72  93
  75  63  47  33  89  24  56  66  78   4   1  78   7  53  86  71   3  77
  92  22  76   8  78  73  76  77  44  21  31  37   8  46  69  58  83  97
  14  11  24  82   8  25  75  93  21  33  13  66  95  61  25  83  98   3
  93  99  11  55  97  83  87  71  67  72  49  55  16   6  18  43  21  49
  23  14  98  54  85  11  97  56  62  57  90  22  97  84  26  15  14  85
  44   7  78  57  60  16  25  10  67  72  54  70  37  22  41  78  92  50
  48  78  41  79  46  88  17  29  46  68  67  79  47   1  30  64  76  36
  54  94  34   3  85  84  49  55  33  29  56  83  32  29  95  75   9 100
  33   9  85  78  51  80  42  65  84  25  21  45  16  31  92  15  20  27
  87   8 100  54  48  61  35  33  20  68  25  84  95  39  48   6  80  64
  88  33  43  75  67  89  99  31  18  69  65  61  79  18  40  36  82  29
  23  39  42  75  78  71  26  49  51  63  45  55   1  87  17  20  10  93
  52  11  69  24  15  64  22  47   4  57  89  81  47  55  80  72  15  78
  16  26  54  85  59  86  30  45  38  23  92  55  77  13  60  27  77  72
  88  40  44  77  39  92  70  99  34  44  27  57  70  74  53  90  28  44
   2  83  95  97  27  85  31  65  23  99  53   4  71  13  40  84  49  62
  71  14  37  24  23  67  93  96  54  10  42  58  89  94  77  83  12  37
  17  31  85  58  36  42  82   3  86  94  37  47  81  28  73  29   3 100
  14  42  37  41  19  98  39  64  47  90   3  99  29  79  76  59  43  27
  22  59  17  93  38  12  23   7  97  15  88  76  36  64  33  92  50   1
  23  98  71  37  19  28  29  53  95  51  47   8  86  17  30  12  62  15
  31   9  41  49  31  24  67  93  65  13  18  34  11  29  76   6  82   6
  43  87  53  58  57  79  88  82  11  73  49  20  13  26]

In [33]:
k = 4
l = (max(idade) - min(idade) + 1)/ k
print(l)

25.0

In [34]:
intervalos = (idade - min(idade)) // l
intervalos_largura_fixa = intervalos.astype(int)
intervalos_largura_fixa

array([1, 0, 2, 0, 3, 0, 3, 2, 0, 0, 3, 2, 0, 1, 2, 0, 0, 3, 0, 1, 1, 0,
       2, 2, 3, 3, 3, 3, 3, 0, 0, 0, 2, 2, 0, 2, 0, 0, 2, 3, 0, 3, 0, 1,
       2, 1, 2, 0, 2, 0, 1, 2, 0, 2, 0, 1, 3, 1, 2, 3, 1, 3, 0, 2, 2, 1,
       3, 3, 0, 1, 1, 0, 0, 2, 0, 1, 1, 2, 3, 1, 0, 1, 1, 0, 0, 0, 3, 1,
       2, 3, 2, 2, 1, 1, 3, 0, 2, 2, 3, 0, 0, 3, 0, 2, 3, 2, 0, 3, 3, 0,
       3, 0, 3, 2, 3, 3, 1, 0, 1, 1, 0, 1, 2, 2, 3, 3, 0, 0, 0, 3, 0, 0,
       2, 3, 0, 1, 0, 2, 3, 2, 0, 3, 3, 0, 3, 3, 0, 2, 3, 3, 3, 2, 2, 2,
       1, 2, 0, 0, 0, 1, 0, 1, 0, 0, 3, 2, 3, 0, 3, 2, 2, 2, 3, 0, 3, 3,
       1, 0, 0, 3, 1, 0, 3, 2, 2, 0, 0, 0, 2, 2, 2, 2, 1, 0, 1, 3, 3, 1,
       1, 3, 1, 3, 1, 3, 0, 1, 1, 2, 2, 3, 1, 0, 1, 2, 3, 1, 2, 3, 1, 0,
       3, 3, 1, 2, 1, 1, 2, 3, 1, 1, 3, 2, 0, 3, 1, 0, 3, 3, 2, 3, 1, 2,
       3, 0, 0, 1, 0, 1, 3, 0, 0, 1, 3, 0, 3, 2, 1, 2, 1, 1, 0, 2, 0, 3,
       3, 1, 1, 0, 3, 2, 3, 1, 1, 2, 2, 3, 3, 1, 0, 2, 2, 2, 3, 0, 1, 1,
       3, 1, 0, 1, 1, 2, 3, 2, 1, 1, 2, 2, 1, 2, 0, 3, 0, 0, 0, 3, 2, 0,
       2, 0, 0, 2, 0, 1, 0, 2, 3, 3, 1, 2, 3, 2, 0, 3, 0, 1, 2, 3, 2, 3,
       1, 1, 1, 0, 3, 2, 3, 0, 2, 1, 3, 2, 3, 1, 1, 3, 1, 3, 2, 3, 1, 1,
       1, 2, 2, 2, 2, 3, 1, 1, 0, 3, 3, 3, 1, 3, 1, 2, 0, 3, 2, 0, 2, 0,
       1, 3, 1, 2, 2, 0, 1, 0, 0, 2, 3, 3, 2, 0, 1, 2, 3, 3, 3, 3, 0, 1,
       0, 1, 3, 2, 1, 1, 3, 0, 3, 3, 1, 1, 3, 1, 2, 1, 0, 3, 0, 1, 1, 1,
       0, 3, 1, 2, 1, 3, 0, 3, 1, 3, 3, 2, 1, 1, 0, 2, 0, 3, 1, 0, 0, 0,
       3, 0, 3, 3, 1, 2, 1, 3, 1, 0, 0, 3, 2, 1, 0, 1, 1, 2, 3, 2, 1, 0,
       3, 0, 1, 0, 2, 0, 1, 0, 1, 1, 1, 0, 2, 3, 2, 0, 0, 1, 0, 1, 3, 0,
       3, 0, 1, 3, 2, 2, 2, 3, 3, 3, 0, 2, 1, 0, 0, 1])

In [35]:
from collections import Counter
Counter(intervalos_largura_fixa)

Counter({1: 124, 0: 133, 2: 111, 3: 132})

Intervalos de Igual Frequência
Neste tipo de discretização a ideia consiste em manter o mesmo número de valores (ou exemplos) em cada intervalo.

Considerando k
o número de intervalos e n

o número de exemplos:

    1.Calculamos N, o número de exemplos por intervalo, como N=nk

    2.Calculamos o ranking dos valores da variável x

    3.Aplicamos o método de discretização de igual tamanho sobre o ranking dos elementos

In [36]:
K = 4
N = np.round(len(idade) / K)

from scipy.stats import rankdata
x = rankdata(idade)

L = (np.max(x) - np.min(x) + 1) / K
intervalos = (x - np.min(x)) // L

intervalos_igual_frequencia = intervalos.astype(int)
print(intervalos_igual_frequencia)

[1 0 2 0 2 0 3 2 0 0 3 2 0 1 2 0 0 3 0 1 1 0 2 2 3 3 3 3 3 0 0 0 2 2 0 2 0
 0 2 3 0 3 0 1 2 1 2 0 2 0 2 2 0 2 1 1 3 1 2 3 1 3 0 2 2 1 3 3 0 1 1 0 0 2
 0 1 1 2 3 1 0 1 1 0 0 0 3 1 2 3 2 2 1 1 3 0 2 2 3 0 0 3 0 2 3 2 0 3 3 0 2
 0 3 2 2 3 1 0 1 1 0 1 2 2 3 3 0 0 0 3 0 1 2 3 0 1 0 2 3 2 1 3 3 0 3 3 0 2
 3 3 3 2 2 2 1 2 0 0 0 1 0 1 0 0 3 2 3 0 3 2 2 2 3 0 3 3 1 0 0 3 1 0 3 2 2
 0 1 0 2 2 2 2 1 0 1 3 3 2 1 3 1 3 1 3 0 1 1 2 2 3 1 0 1 2 2 1 2 3 1 0 3 3
 1 2 1 1 2 3 1 1 3 2 0 3 1 0 3 3 2 3 1 2 3 1 0 1 0 1 3 0 0 1 3 0 3 2 1 2 1
 1 0 2 1 3 3 1 1 0 3 2 3 1 1 2 2 3 3 1 0 2 2 2 3 0 1 1 3 1 0 1 1 2 3 2 1 1
 2 2 1 2 0 3 0 0 0 3 2 0 2 0 0 2 0 1 0 2 3 3 1 2 3 2 0 3 0 1 2 3 2 3 1 1 1
 0 3 2 3 0 2 1 3 2 3 1 1 3 1 3 2 3 1 1 1 2 2 2 2 3 1 1 0 3 3 3 1 3 1 2 0 3
 2 0 2 0 1 3 1 2 2 0 1 0 0 2 3 3 2 0 1 2 3 3 3 3 0 1 0 1 3 2 1 1 3 0 3 3 1
 1 3 1 2 1 0 3 0 1 1 1 0 3 1 2 1 3 0 3 1 3 2 2 1 1 0 2 0 3 1 0 0 0 3 0 3 2
 1 2 1 3 2 0 0 3 2 1 0 1 1 2 3 2 1 0 3 0 1 0 2 0 1 0 1 1 1 0 2 3 2 0 0 1 0
 1 2 0 3 0 1 3 2 2 2 3 3 3 0 2 1 0 0 1]

In [37]:
from collections import Counter
Counter(intervalos)

Counter({1.0: 127, 0.0: 127, 2.0: 121, 3.0: 125})

In [38]:
df = pd.DataFrame({"idade": idade, "rank": x, "intervalos": intervalos_igual_frequencia})
df

     idade   rank  intervalos
0       38  200.5           1
1       13   60.5           0
2       73  360.0           2
3       10   43.5           0
4       76  372.0           2
5        6   22.0           0
6       80  399.5           3
7       65  320.5           2
8       17   86.5           0
9        2    7.0           0
10      77  379.5           3
11      72  354.0           2
12       7   26.5           0
13      26  137.5           1
14      51  260.0           2
15      21  103.0           0
16      19   95.0           0
17      85  427.5           3
18      12   55.5           0
19      29  157.0           1
20      30  163.5           1
21      15   74.0           0
22      51  260.0           2
23      69  337.5           2
24      88  445.0           3
25      88  445.0           3
26      95  476.5           3
27      97  484.0           3
28      87  438.0           3
29      14   67.0           0
..     ...    ...         ...
470     41  212.5           1
471     49  251.0           1
472     31  169.5           1
473     24  124.0           0
474     67  328.5           2
475     93  467.0           3
476     65  320.5           2
477     13   60.5           0
478     18   91.5           0
479     34  184.0           1
480     11   50.0           0
481     29  157.0           1
482     76  372.0           2
483      6   22.0           0
484     82  407.5           3
485      6   22.0           0
486     43  222.5           1
487     87  438.0           3
488     53  266.5           2
489     58  293.0           2
490     57  287.0           2
491     79  395.0           3
492     88  445.0           3
493     82  407.5           3
494     11   50.0           0
495     73  360.0           2
496     49  251.0           1
497     20   98.5           0
498     13   60.5           0
499     26  137.5           1

[500 rows x 3 columns]

Tratamento de Dados Desconhecidos



Abordagens comuns de acordo com (Castro e Ferrari, 2016):

    Ignorar as instância que possuem um ou mais valores ausentes;
    Imputar manualmente valores ausentes
    Usar uma constante global para imputar o valor ausente: para cada atributo escolhe-se um valor para cada atributo
    Imputação do tipo hot-deck ou baseada no objeto mais similar

Conjunto de Dados Original

In [39]:
data = pd.DataFrame(iris['data'], columns=iris['feature_names'], copy=True)
data

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
16                 5.4               3.9                1.3               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
22                 4.6               3.6                1.0               0.2
23                 5.1               3.3                1.7               0.5
24                 4.8               3.4                1.9               0.2
25                 5.0               3.0                1.6               0.2
26                 5.0               3.4                1.6               0.4
27                 5.2               3.5                1.5               0.2
28                 5.2               3.4                1.4               0.2
29                 4.7               3.2                1.6               0.2
..                 ...               ...                ...               ...
120                6.9               3.2                5.7               2.3
121                5.6               2.8                4.9               2.0
122                7.7               2.8                6.7               2.0
123                6.3               2.7                4.9               1.8
124                6.7               3.3                5.7               2.1
125                7.2               3.2                6.0               1.8
126                6.2               2.8                4.8               1.8
127                6.1               3.0                4.9               1.8
128                6.4               2.8                5.6               2.1
129                7.2               3.0                5.8               1.6
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.5               1.8
138                6.0               3.0                4.8               1.8
139                6.9               3.1                5.4               2.1
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
142                5.8               2.7                5.1               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

Índices para remover (to_remove) escolhidos aleatoriamente:

In [40]:
import random
random.seed(1)
to_remove = random.sample(range(0, 150), 30)
print(to_remove)

[34, 145, 16, 65, 30, 126, 115, 120, 97, 53, 24, 124, 7, 99, 110, 0, 114, 68, 58, 26, 81, 137, 5, 3, 83, 69, 1, 142, 112, 48]

Armazenamos em uma variável os valores antes de serem removidos

In [41]:
missing_true = data.loc[to_remove, 'petal length (cm)'].values
print(missing_true)
data.loc[to_remove, 'petal length (cm)'] = None

[1.5 5.2 1.3 4.4 1.6 4.8 5.3 5.7 4.3 4.  1.9 5.7 1.5 4.1 5.1 1.4 5.1 4.5
 4.6 1.6 3.7 5.5 1.7 1.5 5.1 3.9 1.4 5.1 5.5 1.5]

Conjunto de dados, com valores removidos

In [42]:
data

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                NaN               0.2
1                  4.9               3.0                NaN               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                NaN               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                NaN               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                NaN               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
16                 5.4               3.9                NaN               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
22                 4.6               3.6                1.0               0.2
23                 5.1               3.3                1.7               0.5
24                 4.8               3.4                NaN               0.2
25                 5.0               3.0                1.6               0.2
26                 5.0               3.4                NaN               0.4
27                 5.2               3.5                1.5               0.2
28                 5.2               3.4                1.4               0.2
29                 4.7               3.2                1.6               0.2
..                 ...               ...                ...               ...
120                6.9               3.2                NaN               2.3
121                5.6               2.8                4.9               2.0
122                7.7               2.8                6.7               2.0
123                6.3               2.7                4.9               1.8
124                6.7               3.3                NaN               2.1
125                7.2               3.2                6.0               1.8
126                6.2               2.8                NaN               1.8
127                6.1               3.0                4.9               1.8
128                6.4               2.8                5.6               2.1
129                7.2               3.0                5.8               1.6
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                NaN               1.8
138                6.0               3.0                4.8               1.8
139                6.9               3.1                5.4               2.1
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
142                5.8               2.7                NaN               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                NaN               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

Vamos separar as instâncias que conhecemos os valores de todos os atributos (train) e as instâncias que possuem os valores ausentes (missing)

In [43]:
train = data.drop(to_remove, axis=0)
missing = data.loc[to_remove,:]
missing.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
34                 4.9               3.1                NaN               0.2
145                6.7               3.0                NaN               2.3
16                 5.4               3.9                NaN               0.4
65                 6.7               3.1                NaN               1.4
30                 4.8               3.1                NaN               0.2

A partir do conjunto train vamos construir uma regressão para predizer a variável resposta ou target 'sepal length (cm)' utilizando os outros três atributos.

Ajustar uma função na forma y=f(X),
y é a variável resposta ou target. y_train representa y.
X são outros três atributos que podem nos ajudar a prever y. X_train representa X.

In [44]:
target = 'petal length (cm)'
y_train = train[target]
X_train = train.drop(target, axis=1)

Instanciamos um regressor linear e ajustamos a regressão aos dados.

In [45]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [46]:
print('Coeficientes: ', model.coef_)
print('Intercepto: ', model.intercept_)

Coeficientes:  [ 0.70969251 -0.62139171  1.50256363]
Intercepto:  -0.27128316566802635

In [47]:
def regression_to_equation (columns, coefs, intercept, nround = 3):
    coefs = np.round(coefs, nround).astype(str)    
    intercept = np.round(intercept, nround).astype(str)    
    str1 = " + ".join( [(coef + ' x '+ column) for column, coef in zip(columns, coefs)] )        
    return 'y = ' + str1 + ' + ' + intercept;

In [48]:
regression_to_equation(X_train.columns, model.coef_, model.intercept_)

'y = 0.71 x sepal length (cm) + -0.621 x sepal width (cm) + 1.503 x petal width (cm) + -0.271'

Agora vamos tentar adivinhar os valores ausentes

In [49]:
X_missing = missing.drop(target, axis=1)

y_missing_pred = model.predict(X_missing)
y_missing_pred

array([1.58040857, 6.07537789, 1.73865418, 4.66093145, 1.50943932,
       5.09352816, 5.7381918 , 6.09303805, 4.28010717, 4.15615744,
       1.3230218 , 5.58844765, 1.46496031, 3.98740009, 5.35839196,
       1.47379039, 5.71118934, 5.0155941 , 4.56398418, 1.76547303,
       3.64324918, 5.04904915, 1.73865418, 1.36750081, 4.7132161 ,
       3.80233562, 1.64254774, 5.02204669, 5.84583442, 1.49145055])

In [50]:
missing_true

array([1.5, 5.2, 1.3, 4.4, 1.6, 4.8, 5.3, 5.7, 4.3, 4. , 1.9, 5.7, 1.5,
       4.1, 5.1, 1.4, 5.1, 4.5, 4.6, 1.6, 3.7, 5.5, 1.7, 1.5, 5.1, 3.9,
       1.4, 5.1, 5.5, 1.5])

Comparamos os valores preditos com os observados (aqueles que nós removemos inicialmente)

In [51]:
results = pd.DataFrame({'missing_true': missing_true, 'y_missing_pred': y_missing_pred})
results

    missing_true  y_missing_pred
0            1.5        1.580409
1            5.2        6.075378
2            1.3        1.738654
3            4.4        4.660931
4            1.6        1.509439
5            4.8        5.093528
6            5.3        5.738192
7            5.7        6.093038
8            4.3        4.280107
9            4.0        4.156157
10           1.9        1.323022
11           5.7        5.588448
12           1.5        1.464960
13           4.1        3.987400
14           5.1        5.358392
15           1.4        1.473790
16           5.1        5.711189
17           4.5        5.015594
18           4.6        4.563984
19           1.6        1.765473
20           3.7        3.643249
21           5.5        5.049049
22           1.7        1.738654
23           1.5        1.367501
24           5.1        4.713216
25           3.9        3.802336
26           1.4        1.642548
27           5.1        5.022047
28           5.5        5.845834
29           1.5        1.491451

Visualização usando Scatter Plot

In [52]:
results.plot.scatter(x = 'missing_true', y = 'y_missing_pred')

Coeficiente de Correlação de Pearson, R

In [53]:
r = np.corrcoef(results['missing_true'], results['y_missing_pred'])
r[0,1]

0.9850004515270022

Coeficiente de Determinação, R2

In [54]:
r[0,1]**2

0.9702258895083983

Erro Médio Quadrático, EMQ

In [55]:
np.mean((results['missing_true'] - results['y_missing_pred'])**2)

0.10559228954055047

Imputação dos valores ausentes no conjunto de dados

In [56]:
predicted = model.predict( data[data[target].isna()].drop(target, axis =1) )
data.loc[data[target].isna(), target] = np.round(predicted, 1)

In [57]:
data

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.5               0.2
1                  4.9               3.0                1.6               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.4               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
16                 5.4               3.9                1.7               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
22                 4.6               3.6                1.0               0.2
23                 5.1               3.3                1.7               0.5
24                 4.8               3.4                1.3               0.2
25                 5.0               3.0                1.6               0.2
26                 5.0               3.4                1.8               0.4
27                 5.2               3.5                1.5               0.2
28                 5.2               3.4                1.4               0.2
29                 4.7               3.2                1.6               0.2
..                 ...               ...                ...               ...
120                6.9               3.2                6.1               2.3
121                5.6               2.8                4.9               2.0
122                7.7               2.8                6.7               2.0
123                6.3               2.7                4.9               1.8
124                6.7               3.3                5.6               2.1
125                7.2               3.2                6.0               1.8
126                6.2               2.8                5.1               1.8
127                6.1               3.0                4.9               1.8
128                6.4               2.8                5.6               2.1
129                7.2               3.0                5.8               1.6
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.0               1.8
138                6.0               3.0                4.8               1.8
139                6.9               3.1                5.4               2.1
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
142                5.8               2.7                5.0               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                6.1               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

Aula 04/09

In [58]:
import pandas as pd
from sklearn import datasets
iris = datasets.load_iris()
data_iris = pd.DataFrame(iris['data'], columns = iris['feature_names'])
data_iris

data = pd.DataFrame({'X': data_iris["petal length (cm)"], 'Y' : data_iris["petal width (cm)"]})
data2 = pd.DataFrame({'X': data_iris["petal length (cm)"], 'Y' : data_iris["sepal width (cm)"]})

data.head()

     X    Y
0  1.4  0.2
1  1.4  0.2
2  1.3  0.2
3  1.5  0.2
4  1.4  0.2

Gráficos de dispersão para os dois conjuntos de dados

In [59]:

fig, ax = plt.subplots(1, 2, figsize=(17, 6) )

ax[0].scatter(data.X, data.Y,)
ax[0].set_title('data')
ax[0].set_xlabel('X')
ax[0].set_ylabel('Y')

ax[1].scatter(data2.X, data2.Y,)
ax[1].set_title('data2')
ax[1].set_xlabel('X')
ax[1].set_ylabel('Y')

plt.show()

NameError: name 'plt' is not defined

In [ ]:
n = 6
dt = data.sample(n, random_state = 1)
dt2 = data2.sample(n, random_state = 1)
dt.head()

Gráficos de dispersão para as amostras

In [ ]:
fig, ax = plt.subplots(1, 2, figsize=(17,6))

ax[0].scatter(dt.X, dt.Y)
ax[0].set_title('data')
ax[0].set_xlabel('X')
ax[0].set_xlabel('Y')

ax[1].scatter(dt2.X, dt2.Y)
ax[1].set_title('data2')
ax[1].set_xlabel('X')
ax[1].set_xlabel('Y')

plt.show()

In [ ]:
fig, ax = plt.subplots(1, 2, figsize=(17,6))

ax[0].scatter(dt.X, dt.Y)
ax[0].hlines(dt.Y.mean(), xmin = dt.X.min(), xmax = dt.X.max(), linestyles = "--", label='Y.mean')
ax[0].vlines(dt.X.mean(), ymin = dt.Y.min(), ymax = dt.Y.max(), linestyles = "--", label='X.mean')
ax[0].set_title('data')
ax[0].set_xlabel('X')
ax[0].set_xlabel('Y')

ax[1].scatter(dt2.X, dt2.Y)
ax[1].hlines(dt2.Y.mean(), xmin = dt2.X.min(), xmax = dt2.X.max(), linestyles = "--", label='Y.mean')
ax[1].vlines(dt2.X.mean(), ymin = dt2.Y.min(), ymax = dt2.Y.max(), linestyles = "--", label='X.mean')
ax[1].set_title('data2')
ax[1].set_xlabel('X')
ax[1].set_xlabel('Y')

plt.show()

A função abaixo permite desenhar um scatter plot evidenciando o quadrado das diferenças.

In [ ]:
def scatter_square_diff ( dt, ax ) :
    
    from matplotlib.patches import Rectangle
    dt['diffX'] = dt.X - dt.X.mean()
    dt['diffY'] = dt.Y - dt.Y.mean()
   
    ax.scatter(dt.X, dt.Y)
    ax.hlines(dt.Y.mean(), xmin = dt.X.min(), xmax = dt.X.max(), linestyles="--", label='Y.mean')
    ax.vlines(dt.X.mean(), ymin = dt.Y.min(), ymax = dt.Y.max(), linestyles="--", label='X.mean')

    for i in range(0,len(dt)):
        color  = 'blue' if (dt.diffX.iloc[i] * dt.diffY.iloc[i] > 0 ) else 'red'    
        rect = Rectangle( 
            xy = (dt.X.iloc[i], dt.Y.iloc[i]), 
            width = -dt.diffX.iloc[i], 
            height = -dt.diffY.iloc[i], 
            linewidth = 1, edgecolor = color,facecolor = color, alpha = 0.2)
        ax.add_patch(rect)
   
    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.legend()    
    return ax

In [ ]:
fig, ax = plt.subplots(1, 2, figsize=(17, 6) )

ax[0] = scatter_square_diff(dt, ax[0])
ax[0].set_title('dt')

ax[1] = scatter_square_diff(dt2, ax[1])
ax[1].set_title('dt2')

plt.show()



    Os quadrados azuis representam as multiplicações do somatório que retornam valores positivos.
    Os quadrados vermelhos representam as multiplicações do somatório que retornam valores negativos.

No conjunto de dados dt observamos que a soma desses quadrados é:

In [ ]:
dt_soma_quadrados = np.sum((dt.X - dt.X.mean()) * (dt.Y - dt.Y.mean()))
print('dt_soma_quadrados: ', dt_soma_quadrados.round(2))
dt_cov = dt_soma_quadrados / (n - 1)
print('dt_cov: ', dt_cov.round(2))

á no conjunto de dados dt2 observamos que a soma desses quadrados é:

In [ ]:
dt2_soma_quadrados = np.sum((dt.X - dt.X.mean()) * (dt2.Y - dt2.Y.mean()))
print('dt_soma_quadrados: ', dt2_soma_quadrados.round(2))
dt2_cov = dt2_soma_quadrados / (n - 1)
print('dt2_cov: ', dt2_cov.round(2))

A covariância entre as variáveis X e Y do conjunto de dados dt é positiva e algumas vezes maior do que a covariância de X e Y

em dt2 que, por sinal, foi negativa.

Valores de covariância positivos indicam que valores acima da média de uma variável estão associados com valores médios acima da outra variável.

Valores de covariância negativos indicam que valores acima da média de uma variável estão associados com valores médios abaixo da outra variável.

Valores muito diferentes de zero indicam que valores associação entre as variáveis, já valores muito próximos de zero indica pouca associaçao entre as variáveis.

-------------//--------------

Correlação de Pearson para a amostra dt. Observe que existe uma correlação bem forte entre as variáveis X e Y e positiva. Indicando que o valor de uma variável aumenta o valor valor da outra também aumenta.

In [ ]:
dt_cor = dt_cov / (dt.X.std() * dt.Y.std())
dt_cor.round(2)

In [ ]:
dt2_cor = dt2_cov / (dt2.X.std() * dt2.Y.std())
dt2_cor.round(2)

Coeficiente de Determinação: este coeficiente normaliza a correlação entra as variáveis no intervalo [0,1], abstraindo se a correlação é positiva ou negativa. No coeficiente de determinação estamos apenas interessados em saber a dependência entre as variáveis. Seja ρ o coeficiente de correlação entre as variáveis X e Y, o coeficiente de determinação, também chamado de R2, é calculado pelo quadrado do coeficente de correlação, ρ2

Dizemos também que o valor da variável X explica em 98% o valor da variável Y.

In [ ]:
dt_r2 = dt_cor**2
dt_r2.round(2)

Dizemos também que o valor da variável X pode estar explicando %5 o valor da variável Y.

In [ ]:
dt2_r2 = dt2_cor**2
dt2_r2.round(2)

In [ ]:
sepal_length = [1,4,3,5,6,4,3,5,6]

In [ ]:
import matplotlib.pyplot as plt 
plt

In [ ]:
pĺt.plot(sepal_length, sepal_length)

In [ ]:
plt.plot(sepal_length, sepal_length, "o")

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [61]:
from sklearn import datasets
iris = datasets.load_iris()

In [4]:
random_class = np.random.choice (a=['C1','C2','C3'], size = 10, replace = True)
random_class

array(['C2', 'C2', 'C1', 'C3', 'C1', 'C2', 'C3', 'C2', 'C2', 'C3'],
      dtype='<U2')

Exemplo de que os atributos mesmo estando ordenados não altera a entropia

In [6]:
ordenados = sorted(random_class)
ordenados

['C1', 'C1', 'C2', 'C2', 'C2', 'C2', 'C2', 'C3', 'C3', 'C3']

In [7]:
def entropia_valores(valores):
    import collections
    counter = collections.Counter(valores)
    vp = [ (n/len(valores)) for n in counter.values() ]    
    return entropia(vp)

In [11]:
def entropia (vp):
    somatorio = 0;
    for p in vp :
        somatorio += 0 if (p == 0) else p * np.log2(p)    
    return somatorio * (-1)

In [13]:
entropia_valores(ordenados)

1.4854752972273344